server:
  port: 8088

spring:
  application:
    name: cloud-collection-core-service
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:8086
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
#spring:
#  security:
#    enabled: false    
management:
  endpoints:
    web:
      exposure:
        include: refresh, hystrix.stream      
        