server:
  port: 8089

spring:
  application:
    name: cloud-collection-hystrix-dashborad-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    lease-expiration-duration-in-seconds: 5
#    lease-renewal-interval-in-seconds: 5
turbine:
  app-config: CLOUD-COLLECTION-WEB
  cluster-name-expression: new String("default")
  combine-host-port: true
  aggregator:
    cluster-config: default