#web服务
cloud-collection-web:
  image: >-
    registry-vpc.cn-hangzhou.aliyuncs.com/geekluxun-myapp/cloud-collection-web:latest
  ports:
    - '8081:8081'
  restart: always
  environment:
    - LANG=C.UTF-8
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  labels:
    aliyun.scale: '1'
  volumes:
    - '/tmp/data:/data'
  memswap_limit: 0
  shm_size: 0
  memswap_reservation: 0
  kernel_memory: 0
  external_links: 
    - "restserver.local"
  name: cloud-collection-web

#核心服务  
cloud-collection-core-service:
  image: >-
    registry-vpc.cn-hangzhou.aliyuncs.com/geekluxun-myapp/cloud-collection-core-service:latest
  restart: always
  environment:
    - LANG=C.UTF-8
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  labels:
    aliyun.scale: '1'
    aliyun.routing.port_8083: restserver.local
  volumes:
    - '/tmp/data:/data'
  memswap_limit: 0
  shm_size: 0
  memswap_reservation: 0
  kernel_memory: 0
  name: cloud-collection-core-service