
feign:
  hystrix:
    enabled: true
    
spring:
  zipkin:
    base-url: http://localhost:8086
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0    
      
spring:
  application:
    name: cloud-collection-web
          
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, hystrix 