eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8086
spring:
  application:
    name: cloud-collection-api-gateway-service
zuul:
  routes:
    api-a:
      path: /core/**
      serviceId: cloud-collection-core-service