eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8086
spring:
  application:
    name: cloud-collection-trace-service

management:
  metrics:
    web:
      server:
        auto-time-requests: false
    
